services:
  accounts-db:
    image: postgres:16
    container_name: accounts-db
    environment:
      POSTGRES_DB: accounts_db
      POSTGRES_USER: bytebank
      POSTGRES_PASSWORD: bytebank
    ports:
      - "5432:5432"
    volumes:
      - accounts_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME:-bytebank} -d accounts_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bytebank-net

  bytebank-accounts:
    build:
      context: .
    container_name: bytebank-accounts
    depends_on:
      accounts-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://accounts-db:5432/accounts_db
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-bytebank}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-bytebank}
      SPRING_RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: bytebank
      RABBITMQ_PASS: bytebank123
      SPRING_DATA_REDIS_HOST: redis
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    ports:
      - "8082:8082"
    networks:
      - bytebank-net

networks:
  bytebank-net:
    external: true

volumes:
  accounts_data:
