services:
  accounts-db:
    image: postgres:16
    environment:
      POSTGRES_DB: accounts_db
      POSTGRES_USER: ${DB_USERNAME:-bytebank}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-bytebank}
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: bytebank
      RABBITMQ_DEFAULT_PASS: bytebank123
    ports:
      - "5672:5672"
      - "15672:15672"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-accounts
    environment:
      PGADMIN_DEFAULT_EMAIL: thales@email.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"