spring:
  mvc:
    problemdetails:
      enabled: false
  application:
    name: accounts
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/accounts_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: supino2604
server:
  port: 8082